(setq init-file-location (file-name-directory (or load-file-name (buffer-file-name))))
(load-library (format "%sbootstrap.el" init-file-location))
(mapc 'load (file-expand-wildcards (format "%sconfig/*.el" init-file-location)))
(mapc 'load-library (file-expand-wildcards (format "%sconfig/*.el" init-file-location)))

(global-unset-key (kbd "<left>"))
(global-unset-key (kbd "<right>"))
(global-unset-key (kbd "<up>"))
(global-unset-key (kbd "<down>"))
(global-unset-key (kbd "C-v"))
(global-unset-key (kbd "M-s"))
